# This is a basic workflow to help you get started with Actions

name: Copy images

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      packages: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: copy transmission
        run: skopeo copy --all --dest-compress-format zstd:chunked --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} docker://linuxserver/transmission:latest docker://ghcr.io/abihf/zimg/transmission:latest

      - name: copy plex
        run: skopeo copy --all --dest-compress-format zstd:chunked --dest-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} docker://linuxserver/plex:latest docker://ghcr.io/abihf/zimg/plex:latest
